learningwebsite/learning_app/urls.py
from django.contrib import admin
from django.urls import path
from learning_app import views

urlpatterns = [
    path('',views.homepage,name='home'),
    path('signup/', views.signuppage, name='signup'),
    path('login/', views.loginpage, name='login'),
    path('masterlogin/',views.masterloginloginpage,name='masterlogin'),
    path('studentlogin/',views.studentloginloginpage,name='studentlogin'),
    path('masterdashboard/',views.masterdashboardpage,name='masterdashboard'),
    path('studentdashboard/',views.studentdashboardpage,name='studentdashboard'),
    path('logout/', views.logout_view, name='logout'),
]

learningwebsite/learningwebsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_app.urls'))
]

learningwebsite/learning_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    master = models.ForeignKey(User, on_delete=models.CASCADE)

class Answer(models.Model):
    text = models.TextField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)

learningwebsite/learning_app/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .models import Question, Answer

# Create your views here.

def homepage(request):
    if request.method == 'GET' and 'signup' in request.GET:
        return redirect('signup')
    return render(request, 'base.html')

def signuppage(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        user_type = request.POST['user-type']
        # save user info to database
        my_user = User.objects.create_user(name,email,password)
        my_user.save()
        if user_type == 'master':
            return redirect('masterlogin')
        if user_type == 'student':
            return redirect('studentlogin')
        else:
            return HttpResponse('password and confirm password in not matched')
    
    return render(request,'signup.html')

def loginpage(request):
    if request.method == 'POST':
        user_type = request.POST['user-type']

        if user_type == 'master':
            return redirect('masterlogin')
        elif user_type == 'student':
            return redirect('studentlogin')
        else:
            return HttpResponse('password and confirm password in not matched')
    
    return render(request,'signin.html')

def masterloginloginpage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('masterdashboard')
        else:
            return HttpResponse('username or password incorrect')
    return render(request, "master'slogin.html")


def masterdashboardpage(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        if title:  # add this check to ensure title field is not empty
            question = Question.objects.create(title=title, description=description, master=request.user)
            question.save()
    questions = Question.objects.filter(master=request.user)
    context = {'questions': questions}
    return render(request, 'masters_dashboard.html', context)


def studentloginloginpage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('studentdashboard')
        else:
            return HttpResponse('username or password incorrect')
    
    return render(request, "student'slogin.html")

def studentdashboardpage(request):
    questions = Question.objects.all()
    if request.method == 'POST':
        for question in questions:
            answer_text = request.POST.get('answer' + str(question.id))
            if answer_text:
                answer = Answer.objects.create(
                    text=answer_text,
                    question=question,
                    student=request.user
                )
                answer.save()
        return redirect('student_dashboard')
    context = {'questions': questions}
    return render(request, 'student_dashboard.html', context)



def logout_view(request):
    logout(request)
    return redirect('login')



learningwebsite/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Master and Student Task Executor</title>
	<style>
		body {
			background-image: url('https://image.lexica.art/full_jpg/38018175-c509-42e5-acda-8afcedad3987');
			background-size: cover;
			background-position: center;
		}

		nav {
			background-color: rgba(0, 0, 0, 0.7);
			padding: 20px;
		}

		nav ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			overflow: hidden;
		}

		nav li {
			float: left;
		}

		nav li a {
			display: block;
			color: #d2deff;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
		}

		nav li a:hover {
			background-color: #333;
			color: #ffffff;
		}

		nav li:last-child {
			float: right;
		}

        nav li:last-child {
			float: right;
		}

		.banner {
			margin: 100px auto;
			text-align: center;
		}

		.banner h1 {
			font-size: 50px;
			color: #fff;
			animation: fadeIn 2s;
		}

		.banner p {
			font-size: 25px;
			color: #fff;
			animation: fadeIn 2s;
		}

		@keyframes fadeIn {
			from {opacity: 0;}
			to {opacity: 1;}
		}
	</style>
</head>
<body>
	<nav>
	<ul>
		<li><a href="#">students_dashbord</a></li>
		<li><a href="#">teachers_dashbord</a></li>
		<li><a href="#">pdf for previous examinatios</a></li>
		<li><a href="{% url 'login' %}">user login</a></li>
        <li><a href="{% url 'signup' %}">sign up</a></li>
	</ul>
</nav>

	

	<div class="banner">
		<h1>Master and Student Task Executor</h1>
		<p>We help students and masters collaborate and complete their tasks</p>
	</div>

</body>
</html>

learningwebsite/templates/master'slogin.html
<!DOCTYPE html>
<html>
<head>
	<title>log in</title>
	<style>
		body {
			background-image: url('https://image.lexica.art/full_jpg/2864d282-1c29-4032-bb17-2c0aa8b8ff86');
			background-size: cover;
			background-position: center center;
		}
		
		.form-container {
			position: relative;
			z-index: 1;
			background: rgba(255, 255, 255, 0.8);
			padding: 80px 40px;
			border-radius: 100px;
			margin-top: 50px;
		}
	</style>
	
</head>
<body>
	<div class="form-container" style="text-align:center;">
		<form method="post">
			{% csrf_token %}
			<h1>Master's log in page</h1>
			<p>log in here</p>
	
			<label for="name"><b>username</b></label>
			<input type="text" placeholder="Enter username" id="username"name="username"><br><br>
	
			<label for="password"><b>password</b></label>
			<input type="password" placeholder="Enter your password" id="password" name="password"><br><br>

			<button type="submit">log in</button>
		</form>
		<p>Don't an account? <a href="{% url 'signup' %}"> Sign up</a></p>
	</div>

learningwebsite/templates/masters_dashboard.html
<!DOCTYPE html>
<html>
<head>
	<title>My Website</title>
	<style>
		body {
			background-image: url('https://cdn.pixabay.com/photo/2016/01/27/04/32/books-1163695_960_720.jpg');
			background-size: cover;
		}
		
		.container {
			margin: 50px auto;
			max-width: 800px;
			padding: 20px;
			background-color: #906eb364;
			border-radius: 10px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
		}
		
		h1 {
			text-align: center;
			margin-top: 0px;
		}
		
		h2 {
			margin-top: 40px;
			margin-bottom: 20px;
		}
		
		form {
			margin-bottom: 30px;
		}
		
		ul {
			list-style: none;
			padding: 0px;
			margin: 0px;
		}
		
		li {
			margin-bottom: 20px;
			padding: 10px;
			border-radius: 5px;
			box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
		}
		
		.question {
			font-size: 18px;
			font-weight: bold;
			margin-bottom: 10px;
		}
		
		.answer {
			margin-top: 0px;
			margin-bottom: 0px;
		}
	</style>
</head>
<body>
	<header>
		<nav>
			<ul>
				<center><li><a href="#">Master's Dashboard</a></li></center>
				<li style="float: right;"><a href="{% url 'logout' %}">Logout</a></li>
				<li style="float: home;"><a href="{% url 'home' %}">Homepage</a></li>
			</ul>
		</nav>
	</header>
	
	<main>
		<div class="container">
			<h2>Post a question here</h2>
			<form method="POST">
				{% csrf_token %}
				<label for="question">Question:</label><br>
				<textarea id="question" name="question" rows="4" cols="50"></textarea><br><br>
				<input type="submit" value="Post question">
			</form>
			
			<h2>Previous Questions and Answers</h2>
			<ul>
				{% for question in questions %}
				<li>
					<div class="question">{{ question.question }}</div>
					<p class="answer">{{ question.answer }}</p>
				</li>
				{% endfor %}
			</ul>
		</div>
	</main>
	
	<footer>
		<p>&copy; 2023 My Website</p>
	</footer>
</body>
</html>

learningwebsite/templates/signin.html
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>
	<style>
		body {
			background-image: url('https://image.lexica.art/full_jpg/2864d282-1c29-4032-bb17-2c0aa8b8ff86');
			background-size: cover;
			background-position: center center;
		}
		
		.form-container {
			position: relative;
			z-index: 1;
			background: rgba(255, 255, 255, 0.8);
			padding: 80px 40px;
			border-radius: 100px;
			margin-top: 50px;
		}
	</style>
	
</head>
<body>
	<div class="form-container" style="text-align:center;">
		<form method="post">
			{% csrf_token %}
			<h1>login Verification</h1>
			<p>select one</p>
	
            <label for="user-type"><b>login as a:</b></label>
			<select name="user-type">
				<option value="student">Student</option>
				<option value="master">Master</option>
			</select><br><br>
            
			<button type="submit">log in</button>
		</form>
        <p>don't have an account? <a href="{% url 'signup' %}"> Sign up</a></p>
	</div>
</body>
</html>

learningwebsite/templates/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>
	<style>
		body {
			background-image: url('https://image.lexica.art/full_jpg/2864d282-1c29-4032-bb17-2c0aa8b8ff86');
			background-size: cover;
			background-position: center center;
		}
		
		.form-container {
			position: relative;
			z-index: 1;
			background: rgba(255, 255, 255, 0.8);
			padding: 80px 40px;
			border-radius: 100px;
			margin-top: 50px;
		}
	</style>
	
</head>
<body>
	<div class="form-container" style="text-align:center;">
		<form method="post">
			{% csrf_token %}
			<h1>Sign Up</h1>
			<p>Please fill in this form to create an account. Make your profile here . If you have already an account click login.</p>
	
			<label for="name"><b>Name</b></label>
			<input type="text" placeholder="Enter your name" name="name" required><br><br>
	
			<label for="email"><b>Email</b></label>
			<input type="email" placeholder="Enter your email" name="email" required><br><br>
	
			<label for="password"><b>Password</b></label>
			<input type="password" placeholder="Enter your password" name="password" required><br><br>
	
			<label for="password-repeat"><b>Repeat Password</b></label>
			<input type="password" placeholder="Repeat your password" name="password-repeat" required><br><br>
	
            <label for="user-type"><b>Register as a:</b></label>
			<select name="user-type">
				<option value="student">Student</option>
				<option value="master">Master</option>
			</select><br><br>
            
			<button type="submit">Sign Up</button>
		</form>
		<p>Already have an account? <a href="{% url 'login' %}"> Sign In</a></p>
	</div>
</body>
</html>

learningwebsite/templates/student'slogin.html
<!DOCTYPE html>
<html>
<head>
	<title>log in</title>
	<style>
		body {
			background-image: url('https://image.lexica.art/full_jpg/2864d282-1c29-4032-bb17-2c0aa8b8ff86');
			background-size: cover;
			background-position: center center;
		}
		
		.form-container {
			position: relative;
			z-index: 1;
			background: rgba(255, 255, 255, 0.8);
			padding: 80px 40px;
			border-radius: 100px;
			margin-top: 50px;
		}
	</style>
	
</head>
<body>
	<div class="form-container" style="text-align:center;">
		<form method="post">
			{% csrf_token %}
			<h1>student's log in page</h1>
			<p>log in here</p>
	
			<label for="name"><b>username</b></label>
			<input type="text" placeholder="Enter username" id="username"name="username"><br><br>
	
			<label for="password"><b>password</b></label>
			<input type="password" placeholder="Enter your password" id="password" name="password"><br><br>

			<button type="submit">log in</button>
		</form>
		<p>Don't an account? <a href="{% url 'signup' %}"> Sign up</a></p>
	</div>

learningwebsite/templates/student_dashboard.html
<!DOCTYPE html>
<html>
<head>
	<title>My Website</title>
	<style>
		body {
			background-image: url('https://image.lexica.art/full_jpg/38018175-c509-42e5-acda-8afcedad3987');
			background-size: cover;
		}
		
		.container {
			margin: 50px auto;
			max-width: 600px;
			padding: 10px;
			background-color: #87308e62;
			border-radius: 10px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
		}
		
		h1 {
			text-align: center;
			margin-top: 0px;
		}
		
		h2 {
			margin-top: 40px;
			margin-bottom: 20px;
		}
		
		form {
			margin-bottom: 30px;
		}
		
		ul {
			list-style: none;
			padding: 0px;
			margin: 0px;
		}
		
		li {
			margin-bottom: 20px;
			padding: 10px;
			border-radius: 5px;
			box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
		}
		
		.question {
			font-size: 18px;
			font-weight: bold;
			margin-bottom: 10px;
		}
		
		.answer {
			margin-top: 0px;
			margin-bottom: 0px;
		}
	</style>
</head>
<body>
	<header>
		<nav>
			<ul>
				<center><li><a href="#">Student's Dashboard</a></li></center>
				<li style="float: right;"><a href="{% url 'login' %}">Logout</a></li>
				<li style="float: home;"><a href="{% url 'home' %}">Homepage</a></li>
			</ul>
		</nav>
	</header>
	
	<main>
		<div class="container">
			<h2>Questions to Answer</h2>
			<ul>
				{% for question in questions %}
					<li>
						<div class="question">{{ question.title }}</div>
						<form method="POST">
							{% csrf_token %}
							<label for="answer{{ question.id }}">Answer:</label><br>
							<textarea id="answer{{ question.id }}" name="answer{{ question.id }}" rows="4" cols="50"></textarea><br><br>
							<input type="submit" value="Submit answer">
						</form>
						{% for answer in question.answer_set.all %}
							<div class="answer">{{ answer.text }}</div>
						{% endfor %}
					</li>
				{% endfor %}
				</ul>				
		</div>
	</main>
	
	<footer>
		<p>&copy; 2023 My Website</p>
	</footer>
</body>
</html>